version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    command:
      --default-authentication-plugin=mysql_native_password
      --init-file=/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql
  ti-community-bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    entrypoint: npm run dev
    depends_on:
      - db
    links:
      - db
    ports:
      - 3100:3100
    volumes:
      # Mount the directory so live reload works.
      - .:/usr/src/app
volumes:
  mysql-data:
