version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    command:
      --default-authentication-plugin=mysql_native_password
      --init-file=/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
